export const inputDataPendaftaran = {
  Kode_Asal: "1",
  Kode_Masuk: "2",
  Kode_Datang: "2",
  Kode_Kondisi: "2",
  No_MR: "",
  Kode_Bayar: "2",
  KodeRekanan: "",
  NIK: "",
  No_Kartu: "",
  Referensi: "",
  Kode_Referensi: "0",
  Medis: "RAWAT JALAN",
  PermintaanDPJP: "RUJUKAN DIRI SENDIRI",
  Kode_Dokter: null,
  SourcePasien: "",
  Kode_Source: "",
  CaraMasuk_IGD: "",
  nomorasalrujukan: "",
  kodeproviderasalrujukan: null,
  tanggalasalrujukan: null,
  kodediagnosautama: null,
}

